version: '3.7'
services:

  gerrit:
    ports:
      - "8082:8080"
      - "29418:29418"
    volumes:
      - gerrit-git-volume:/var/gerrit/git
      - gerrit-index-volume:/var/gerrit/index
      - gerrit-cache-volume:/var/gerrit/cache
    image: gerritcodereview/gerrit:latest
    environment:
      - CANONICAL_WEB_URL=http://192.168.99.100
