version: '3.7'
services:

  prometheus:
    extends:
      service: prometheus
      file: ../prometheus/docker-compose.yml
    ports:
      - 9090:9090

  grafana:
    depends_on:
      - prometheus
    image: docker.io/grafana/grafana:8.1.0
    volumes:
      # Interesting paths
      # GF_PATHS_CONFIG         /etc/grafana/grafana.ini
      # GF_PATHS_DATA           /var/lib/grafana
      # GF_PATHS_HOME           /usr/share/grafana
      # GF_PATHS_LOGS           /var/log/grafana
      # GF_PATHS_PLUGINS        /var/lib/grafana/plugins
      # GF_PATHS_PROVISIONING   /etc/grafana/provisioning
      # database and plugins
#      - type: volume
#        source: grafanaStorage
#        target: /var/lib/grafana
      - type: bind
        source: ./grafana.ini
        target: /etc/grafana/grafana.ini
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboards/:/etc/dashboards/
      - ./dashboards.yml/:/etc/grafana/provisioning/dashboards/dashboards.yml
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - 3000:3000
