version: '3.7'
services:

  prometheus:
    extends:
      service: prometheus
      file: ../prometheus/docker-compose.yml
    ports:
      - 9090:9090

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:7.5.2
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./dashboards/:/etc/dashboards/
      - ./dashboards.yml/:/etc/grafana/provisioning/dashboards/dashboards.yml
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - 3000:3000
