version: "3"
services:
  zipkin:
    hostname: zipkin
    image: docker.io/openzipkin/zipkin:2.9.4
    ports:
      - target: 9411
        published: 9411
  nginx:
    image: docker.io/opentracing/nginx-opentracing:0.19.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./zipkin-config.json:/etc/zipkin-config.json
    ports:
      - target: 8081
        published: 8081
volumes:
  grafanaStorage: {}