version: '3.7'
services:
  elasticsearch:
    ports:
      - '9200:9200'
      - '9300:9300'
    image: elasticsearch:7.12.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    # ports:
    # - "9200:9200"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
    # volumes:
    #   - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

  elasticsearch_hq:
    extends:
      service: elasticsearch_hq
      file: ../elasticsearch_hq/docker-compose.yml
    ports:
      - '5000:5000'
    depends_on:
      - elasticsearch

# volumes:
#   elasticsearch_data: {}
