version: '3.3'
services:
  mongo-express:
    # ports:
    #   - '8081:8081'
    # depends_on:
    #   - mongo
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    image: mongo-express:0.54.0
