# Requires PostgreSQL version 10
version: "3.2"
services:
  confluence:
    image: "docker.io/atlassian/confluence-server:7.13.0-rc1-jdk11"
    volumes:
      - confluence:/var/atlassian/application-data/confluence
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - database

volumes:
  confluence: {}
