version: "3.2"
services:
  vault:
    image: "vault:1.6.3"
    cap_add:
      - IPC_LOCK
    entrypoint: /mnt/init/init.sh
    # Original command parameters are no longer relevant
    command: []
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "vault_development_token"
      # Accessible at http://localhost:8200/ui
      VAULT_LOCAL_CONFIG: '{"ui": true}'
      VAULT_ADDR: "http://localhost:8200"
      APPLICATION_NAME: "example"
    ports:
    - 8200:8200
    volumes:
      - "./vault/:/mnt/init"

  vault_ui:
    extends:
      service: vault_ui
      file: ../vault_ui/docker-compose.yml
    ports:
      - '8000:8000'
    depends_on:
      - vault
