version: "3.2"
services:
  # https://hub.docker.com/r/djenriquez/vault-ui
  vault_ui:
    # ports:
    #   - '8000:8000'
    image: vault:0.9.5
    environment:
      - VAULT_URL_DEFAULT=http://vault:8200
      - VAULT_AUTH_DEFAULT=TOKEN
    # depends_on:
    #   - vault
