version: '3.7'
services:
  mockServer:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_MAX_EXPECTATIONS: 100
      MOCKSERVER_MAX_HEADER_SIZE: 8192
