# Requires PostgreSQL
version: "3.0"

# https://hub.docker.com/_/sonarqube
services:
  sonarqube:
    image: docker.io/sonarqube:8.8-community
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://database:5432/<Database name>
      SONARQUBE_JDBC_USERNAME: <Database username>
      SONARQUBE_JDBC_PASSWORD: <Database password>
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

networks:
  sonarnet:

volumes:
  sonarqube_conf: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_bundled-plugins: {}
