# Requires PostgreSQL version 11
version: '3.2'
services:
  xwiki:
    image: "docker.io/xwiki:lts-postgres-tomcat"
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_USER=<Database user>
      - DB_PASSWORD=<Database password>
      - DB_DATABASE=<Database name>
    volumes:
      - xwiki:/usr/local/xwiki
    depends_on:
      - database

volumes:
  xwiki: {}