version: "3.9"
services:
  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: docker.io/bitnami/kafka:2.7.0
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "true"
    # depends_on:
    #   - zookeeper
    # volumes:
    #   - kafka:/bitnami/kafka


# volumes:
#   kafka: {}
