version: '3.3'
services:
  redis:
    # volumes:
    #   - 'redis_data:/data'
    image: redis-server:6.2.1-alpine3.13
    # ports:
    #   - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis_commander:
    extends:
      service: redis_commander
      file: ../redis-commander/docker-compose.yml
    ports:
      - "8081:8081"
    depends_on:
      - redis

# volumes:
#   redis_data: {}
