version: "3.9"
services:

  zookeeper_load_balancer:
    extends:
      service: nginx
      file: ../nginx/docker-compose.yml
    volumes:
      - ./load-balancer.conf:/etc/nginx/nginx.conf:ro
    # ports:
    #   - "2181:2181"
    #   - "8080:8080"
